# Site wide configuration

title: Kim Woo Jin
locale: ko_KR
description: Learning by Doing.
logo: site-logo.png
search: true
# url: http://woogenius.me 


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: WooGenius
  avatar: site-logo.png
  email: woog2nius@gmail.com
  disqus-shortname: woogenius
  twitter: woogenius
  facebook: woogenius
  github: WooGenius
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: woogenius
  instagram: #username
  flickr: #username
  tumblr: #username
  mail : woog2nius@gmail.com
  google:
    plus: #username
    analytics: UA-57649737-1
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
